### PR TITLE
Remove intern notice

### PR DESCRIPTION
**Pull request by EcoLek**
Hiding the internship notices from the public website.

### CODE REVIEW

**Comment by gkang2018** [comment]
looks good to me! I was just wondering if it's worth keeping the part of the homepage where it has a link that says "Apply for the Summer 2021 Internship Program." and then the link is dead bc the submission has past. We should just get rid of that as well right?

**Comment by EcoLek** [comment]
@gkang2018 yeah, sounds like I missed an on page reference. Let me take care of that.

**Comment by EcoLek** [comment]
@gkang2018 should be done. Merge?

**Comment by gkang2018** [comment]
> @gkang2018 should be done. Merge?

lgtm!

**Review by gkang2018 — APPROVED** [review]

**Pull request merged**
